// Demo inventory data for canteen ingredients
export const inventoryData = [
  {
    id: 1,
    name: "Tomatoes",
    category: "Vegetables",
    currentStock: 45,
    minStock: 20,
    maxStock: 100,
    unit: "kg",
    costPerUnit: 196,
    supplier: "Fresh Farm Co.",
    lastUpdated: "2025-08-30",
  },
  {
    id: 2,
    name: "Chicken Breast",
    category: "Meat",
    currentStock: 25,
    minStock: 15,
    maxStock: 80,
    unit: "kg",
    costPerUnit: 727,
    supplier: "Premium Meats Ltd.",
    lastUpdated: "2025-08-29",
  },
  {
    id: 3,
    name: "Mozzarella Cheese",
    category: "Dairy",
    currentStock: 12,
    minStock: 8,
    maxStock: 50,
    unit: "kg",
    costPerUnit: 895,
    supplier: "Dairy Direct",
    lastUpdated: "2025-08-28",
  },
  {
    id: 4,
    name: "Olive Oil",
    category: "Pantry",
    currentStock: 8,
    minStock: 5,
    maxStock: 30,
    unit: "L",
    costPerUnit: 476,
    supplier: "Mediterranean Imports",
    lastUpdated: "2025-08-27",
  },
  {
    id: 5,
    name: "Rice",
    category: "Grains",
    currentStock: 150,
    minStock: 50,
    maxStock: 200,
    unit: "kg",
    costPerUnit: 85,
    supplier: "Rice Masters Inc.",
    lastUpdated: "2025-08-30",
  },
  {
    id: 6,
    name: "Onions",
    category: "Vegetables",
    currentStock: 35,
    minStock: 25,
    maxStock: 80,
    unit: "kg",
    costPerUnit: 120,
    supplier: "Fresh Farm Co.",
    lastUpdated: "2025-08-29",
  },
  {
    id: 7,
    name: "Ground Beef",
    category: "Meat",
    currentStock: 18,
    minStock: 10,
    maxStock: 60,
    unit: "kg",
    costPerUnit: 650,
    supplier: "Premium Meats Ltd.",
    lastUpdated: "2025-08-28",
  },
  {
    id: 8,
    name: "Fresh Milk",
    category: "Dairy",
    currentStock: 40,
    minStock: 20,
    maxStock: 100,
    unit: "L",
    costPerUnit: 95,
    supplier: "Dairy Direct",
    lastUpdated: "2025-08-30",
  },
  {
    id: 9,
    name: "Salt",
    category: "Seasonings",
    currentStock: 15,
    minStock: 5,
    maxStock: 25,
    unit: "kg",
    costPerUnit: 45,
    supplier: "Spice World",
    lastUpdated: "2025-08-25",
  },
  {
    id: 10,
    name: "Black Pepper",
    category: "Seasonings",
    currentStock: 3,
    minStock: 2,
    maxStock: 10,
    unit: "kg",
    costPerUnit: 850,
    supplier: "Spice World",
    lastUpdated: "2025-08-26",
  },
  {
    id: 11,
    name: "Pasta",
    category: "Grains",
    currentStock: 75,
    minStock: 30,
    maxStock: 120,
    unit: "kg",
    costPerUnit: 125,
    supplier: "Italian Imports",
    lastUpdated: "2025-08-29",
  },
  {
    id: 12,
    name: "Cooking Oil",
    category: "Pantry",
    currentStock: 22,
    minStock: 10,
    maxStock: 40,
    unit: "L",
    costPerUnit: 180,
    supplier: "Oil Co. Ltd.",
    lastUpdated: "2025-08-28",
  },
];

export const categories = [
  "All Categories",
  "Vegetables",
  "Meat",
  "Dairy",
  "Pantry",
  "Grains",
  "Seasonings",
];
