// Demo data for orders - now based on allcustomersDemoData.js
export const ordersData = [
  {
    id: "001",
    status: "preparing",
    customer: "John Doe",
    phone: "(+63) 123-4567",
    total: "₱ 32.98",
    orderedTime: "12:30 PM",
    rating: 5,
    feedback: "Order was ready exactly on time! Great service.",
    date: "1/8/2024",
    items: [
      {
        name: "Margherita Pizza",
        price: "₱ 16.99",
        instructions: "Extra basil, thin crust",
      },
      { name: "Coca Cola", price: "₱ 7.00" },
      { name: "Tiramisu", price: "₱ 8.99" },
    ],
  },
  {
    id: "002",
    status: "ready",
    customer: "Jane Smith",
    phone: "(+63) 123-4567",
    total: "₱ 45.50",
    orderedTime: "12:30 PM",
    rating: 4,
    feedback: "Order was ready exactly on time! Great service.",
    date: "1/8/2024",
    items: [
      {
        name: "Pepperoni Pizza",
        price: "₱ 18.99",
        instructions: "Extra cheese, well done",
      },
      { name: "Orange Juice", price: "₱ 8.00" },
      { name: "Chocolate Cake", price: "₱ 18.51" },
    ],
  },
  {
    id: "003",
    status: "pending",
    customer: "Mike Johnson",
    phone: "(+63) 123-4567",
    total: "₱ 28.75",
    orderedTime: "12:30 PM",
    rating: 3,
    feedback: "Order was ready exactly on time! Great service.",
    date: "1/8/2024",
    items: [
      {
        name: "Hawaiian Pizza",
        price: "₱ 15.99",
        instructions: "Light pineapple, extra ham",
      },
      { name: "Iced Tea", price: "₱ 5.00" },
      { name: "Garlic Bread", price: "₱ 7.76" },
    ],
  },
  {
    id: "004",
    status: "completed",
    customer: "Sarah Wilson",
    phone: "(+63) 123-4567",
    total: "₱ 52.25",
    orderedTime: "11:45 AM",
    completedTime: "12:20 PM",
    rating: 5,
    feedback: "Amazing food quality and fast delivery. Highly recommend!",
    date: "1/8/2024",
    items: [
      {
        name: "Supreme Pizza",
        price: "₱ 22.99",
        instructions: "No onions, extra olives",
      },
      { name: "Sprite", price: "₱ 7.00" },
      { name: "Cheesecake", price: "₱ 22.26" },
    ],
  },
  {
    id: "005",
    status: "cancelled",
    customer: "David Brown",
    phone: "(+63) 123-4567",
    total: "₱ 41.20",
    orderedTime: "11:45 AM",
    cancelledTime: "12:45 PM",
    cancelReason: "Customer requested cancellation - dietary restrictions",
    rating: 2,
    feedback:
      "Had to cancel due to dietary restrictions, but customer service was understanding.",
    date: "1/8/2024",
    items: [
      {
        name: "Meat Lovers Pizza",
        price: "₱ 24.99",
        instructions: "Extra spicy, double meat",
      },
      { name: "Coke", price: "₱ 7.00" },
      { name: "Brownies", price: "₱ 9.21" },
    ],
  },
  {
    id: "006",
    status: "preparing",
    customer: "Lisa Garcia",
    phone: "(+63) 123-4567",
    total: "₱ 38.75",
    orderedTime: "1:15 PM",
    rating: 5,
    feedback: "Perfect vegetarian options! Love the fresh ingredients.",
    date: "1/8/2024",
    items: [
      {
        name: "Veggie Supreme Pizza",
        price: "₱ 19.99",
        instructions: "Extra mushrooms, no peppers",
      },
      { name: "Lemonade", price: "₱ 6.50" },
      { name: "Caesar Salad", price: "₱ 12.26" },
    ],
  },
  {
    id: "007",
    status: "ready",
    customer: "Robert Martinez",
    phone: "(+63) 123-4567",
    total: "₱ 29.99",
    orderedTime: "1:00 PM",
    rating: 4,
    feedback: "Great BBQ flavor, could use a bit more sauce next time.",
    date: "1/8/2024",
    items: [
      {
        name: "BBQ Chicken Pizza",
        price: "₱ 17.99",
        instructions: "Extra BBQ sauce",
      },
      { name: "Water", price: "₱ 3.00" },
      { name: "Mozzarella Sticks", price: "₱ 9.00" },
    ],
  },
  {
    id: "008",
    status: "pending",
    customer: "Amanda Lee",
    phone: "(+63) 123-4567",
    total: "₱ 56.50",
    orderedTime: "1:30 PM",
    rating: 5,
    feedback: "Excellent cheese blend! The wings were perfectly cooked too.",
    date: "1/8/2024",
    items: [
      {
        name: "Four Cheese Pizza",
        price: "₱ 21.99",
        instructions: "Light sauce, extra parmesan",
      },
      { name: "Fresh Orange Juice", price: "₱ 9.00" },
      { name: "Chicken Wings", price: "₱ 15.99" },
      { name: "Apple Pie", price: "₱ 9.52" },
    ],
  },
  // Adding more orders with ratings for better distribution
  {
    id: "009",
    status: "completed",
    customer: "Emily Davis",
    phone: "(+63) 123-4567",
    total: "₱ 34.50",
    orderedTime: "2:00 PM",
    completedTime: "2:25 PM",
    rating: 5,
    feedback:
      "First time ordering here and I'm impressed! Will definitely order again.",
    date: "1/8/2024",
    items: [
      { name: "Margherita Pizza", price: "₱ 16.99" },
      { name: "Garlic Bread", price: "₱ 7.76" },
      { name: "Iced Tea", price: "₱ 5.00" },
      { name: "Tiramisu", price: "₱ 8.99" },
    ],
  },
  {
    id: "010",
    status: "completed",
    customer: "Chris Taylor",
    phone: "(+63) 123-4567",
    total: "₱ 42.75",
    orderedTime: "2:15 PM",
    completedTime: "2:45 PM",
    rating: 4,
    feedback: "Good food and reasonable prices. Delivery was on time.",
    date: "1/8/2024",
    items: [
      { name: "Pepperoni Pizza", price: "₱ 18.99" },
      { name: "Chicken Wings", price: "₱ 15.99" },
      { name: "Coca Cola", price: "₱ 7.00" },
    ],
  },
  {
    id: "011",
    status: "completed",
    customer: "Maria Rodriguez",
    phone: "(+63) 123-4567",
    total: "₱ 28.25",
    orderedTime: "3:00 PM",
    completedTime: "3:30 PM",
    rating: 5,
    feedback:
      "Love the authentic flavors! Customer service was also very helpful.",
    date: "1/8/2024",
    items: [
      { name: "Hawaiian Pizza", price: "₱ 15.99" },
      { name: "Sprite", price: "₱ 7.00" },
      { name: "Garlic Bread", price: "₱ 7.76" },
    ],
  },
  {
    id: "012",
    status: "completed",
    customer: "Alex Thompson",
    phone: "(+63) 123-4567",
    total: "₱ 31.50",
    orderedTime: "3:30 PM",
    completedTime: "4:00 PM",
    rating: 5,
    feedback:
      "Quick service and delicious food. The pizza was still hot when delivered!",
    date: "1/8/2024",
    items: [
      { name: "BBQ Chicken Pizza", price: "₱ 17.99" },
      { name: "Mozzarella Sticks", price: "₱ 9.00" },
      { name: "Lemonade", price: "₱ 6.50" },
    ],
  },
  {
    id: "013",
    status: "completed",
    customer: "Jessica White",
    phone: "(+63) 123-4567",
    total: "₱ 47.25",
    orderedTime: "4:00 PM",
    completedTime: "4:30 PM",
    rating: 4,
    feedback:
      "Great variety of toppings. Would love to see more vegetarian options.",
    date: "1/8/2024",
    items: [
      { name: "Supreme Pizza", price: "₱ 22.99" },
      { name: "Caesar Salad", price: "₱ 12.26" },
      { name: "Fresh Orange Juice", price: "₱ 9.00" },
      { name: "Brownies", price: "₱ 9.21" },
    ],
  },
  {
    id: "014",
    status: "completed",
    customer: "Kevin Anderson",
    phone: "(+63) 123-4567",
    total: "₱ 39.99",
    orderedTime: "4:30 PM",
    completedTime: "5:00 PM",
    rating: 5,
    feedback:
      "Consistently good quality! Been ordering for weeks and never disappointed.",
    date: "1/8/2024",
    items: [
      { name: "Four Cheese Pizza", price: "₱ 21.99" },
      { name: "Garlic Bread", price: "₱ 7.76" },
      { name: "Iced Tea", price: "₱ 5.00" },
      { name: "Cheesecake", price: "₱ 22.26" },
    ],
  },
  {
    id: "015",
    status: "completed",
    customer: "Michael Brown",
    phone: "(+63) 123-4567",
    total: "₱ 25.50",
    orderedTime: "5:00 PM",
    completedTime: "5:25 PM",
    rating: 3,
    feedback: "Food was okay, but delivery took longer than expected.",
    date: "1/8/2024",
    items: [
      { name: "Margherita Pizza", price: "₱ 16.99" },
      { name: "Water", price: "₱ 3.00" },
      { name: "Garlic Bread", price: "₱ 7.76" },
    ],
  },
  {
    id: "016",
    status: "completed",
    customer: "Sophie Miller",
    phone: "(+63) 123-4567",
    total: "₱ 44.75",
    orderedTime: "5:30 PM",
    completedTime: "6:00 PM",
    rating: 5,
    feedback:
      "Outstanding service! The food arrived hot and fresh. Highly recommend!",
    date: "1/8/2024",
    items: [
      { name: "Meat Lovers Pizza", price: "₱ 24.99" },
      { name: "Chicken Wings", price: "₱ 15.99" },
      { name: "Coca Cola", price: "₱ 7.00" },
    ],
  },
  {
    id: "017",
    status: "completed",
    customer: "Daniel Wilson",
    phone: "(+63) 123-4567",
    total: "₱ 36.25",
    orderedTime: "6:00 PM",
    completedTime: "6:30 PM",
    rating: 4,
    feedback: "Good food quality and portion sizes. Will order again soon.",
    date: "1/8/2024",
    items: [
      { name: "Veggie Supreme Pizza", price: "₱ 19.99" },
      { name: "Mozzarella Sticks", price: "₱ 9.00" },
      { name: "Lemonade", price: "₱ 6.50" },
    ],
  },
  {
    id: "018",
    status: "completed",
    customer: "Rachel Green",
    phone: "(+63) 123-4567",
    total: "₱ 33.50",
    orderedTime: "6:30 PM",
    completedTime: "7:00 PM",
    rating: 5,
    feedback: "Amazing taste! The crust was perfect and toppings were fresh.",
    date: "1/8/2024",
    items: [
      { name: "Hawaiian Pizza", price: "₱ 15.99" },
      { name: "Caesar Salad", price: "₱ 12.26" },
      { name: "Sprite", price: "₱ 7.00" },
    ],
  },
  {
    id: "019",
    status: "completed",
    customer: "Thomas Clark",
    phone: "(+63) 123-4567",
    total: "₱ 29.75",
    orderedTime: "7:00 PM",
    completedTime: "7:25 PM",
    rating: 4,
    feedback: "Solid pizza joint. Good value for money and tasty food.",
    date: "1/8/2024",
    items: [
      { name: "BBQ Chicken Pizza", price: "₱ 17.99" },
      { name: "Garlic Bread", price: "₱ 7.76" },
      { name: "Water", price: "₱ 3.00" },
    ],
  },
];
